### ISSUE TITLE
Fix Dead Links in README

### ISSUE THREAD

**Issue by aashutoshrathi** [jboss-outreach/facebook-meme-bot#14]
No sample `Procfile` is added, while we have links in README for that.

**Comment by vijay35** [comment]
Hi @aashutoshrathi I have created the Procfile ..check this PR : https://github.com/jboss-outreach/facebook-meme-bot/pull/21

**Comment by vijay35** [comment]
Hi @aashutoshrathi  check this PR for Procfile.windows : https://github.com/jboss-outreach/facebook-meme-bot/pull/23

**Comment by aashutoshrathi** [comment]
Fixed by @vijay35
